# Generated by Django 4.1.5 on 2023-01-14 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.PositiveBigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'ordering': ['company', 'date'],
            },
        ),
    ]
