# Generated by Django 4.1.5 on 2023-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_stockmarket_rename_businessday_companyday_marketday'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockmarket',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
