# Generated by Django 4.1.5 on 2023-01-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_slug_stockmarket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_day', to='companies.company'),
        ),
    ]
