# Generated by Django 4.1.5 on 2023-01-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companyday_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketday',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_day', to='companies.stockmarket'),
        ),
    ]
